# Generated by Django 4.1.2 on 2022-10-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropCultivation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropcultivation',
            name='intro',
            field=models.TextField(null=True),
        ),
    ]
